version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  skip-dirs:
    - vendor

linters:
  default: none
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - contextcheck
    - depguard
    - dogsled
    - errname
    - exportloopref
    - gosec
    - misspell
    - nakedret
    - nilerr
    - noctx
    - revive
    - typecheck
    - unconvert
    - unparam
    - whitespace

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/pkg/errors"
            desc: "use standard errors package"
  misspell:
    locale: US
  revive:
    min-confidence: 0.8
  gosec:
    excludes:
      - G404 # Use of weak random number generator - acceptable for tests

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - errcheck

    # Exclude some gosec messages
    - linters:
        - gosec
      text: "G404"

  # Maximum issues count per one linter
  max-issues-per-linter: 0

  # Maximum count of issues with the same text
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
      path: stdout
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
